# Generated by Django 2.2.24 on 2021-11-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_solicitudes', '0003_auto_20211108_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.TextField(default='Perez'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(default='Pepe'),
        ),
    ]
