# Generated by Django 2.2.24 on 2021-11-16 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_solicitudes', '0004_auto_20211110_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.TextField(default='+569 7777 7777'),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='verificacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel_solicitudes.Verificacion'),
        ),
    ]
