# Generated by Django 2.2.24 on 2021-11-26 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_solicitudes', '0007_auto_20211116_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilmaestro',
            name='tareas',
            field=models.ManyToManyField(to='panel_solicitudes.Tarea'),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComentarioSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariossolicitud', to='panel_solicitudes.SolicitudTarea')),
            ],
        ),
    ]
