# Generated by Django 2.2.24 on 2021-11-27 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_solicitudes', '0008_auto_20211126_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioMaestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosmaestro', to='panel_solicitudes.PerfilMaestro')),
            ],
        ),
    ]
