# Generated by Django 2.2.24 on 2021-11-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_solicitudes', '0009_comentariomaestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtarea',
            name='perfil_maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudtarea', to='panel_solicitudes.PerfilMaestro'),
        ),
    ]
