# Generated by Django 2.2.24 on 2021-12-07 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_solicitudes', '0010_auto_20211129_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='comentariomaestro',
            name='text',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='comentariosolicitud',
            name='text',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='direccion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='nombre',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='tarea',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.TextField(default='Perez', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.TextField(default='+56977777777', max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(default='Pepe', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.TextField(max_length=12),
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
