# Generated by Django 2.2.24 on 2021-12-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_solicitudes', '0011_auto_20211207_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='estrellas',
            field=models.TextField(),
        ),
    ]
