# Generated by Django 2.2.24 on 2021-12-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_solicitudes', '0013_solicitudtarea_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtarea',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel_solicitudes.Comuna'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel_solicitudes.Comuna'),
        ),
    ]
