# Generated by Django 2.2.24 on 2021-12-09 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel_solicitudes', '0014_auto_20211207_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
